---
title: "posterpoller"
output: html_document
runtime: shiny
resource_files:
- .secrets/3db8733ded05fd02b7eb9bbac30624d9_cansav09@gmail.com
- README.md
---


```{r global, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(gsheet)
library(magrittr)
library(shiny)
library(googlesheets4)
library(googledrive)

authenticate <- function() {
  # designate project-specific cache
  options(gargle_oauth_cache = ".secrets")

  # check the value of the option, if you like
  gargle::gargle_oauth_cache()

  if (interactive()) {
    googlesheets4::gs4_deauth()
    googlesheets4::gs4_auth(
      email = "cansav09@gmail.com",
      path = NULL,
      scopes = c("https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"),
      # Get new token if it doesn't exist
      cache = ".secrets/",
      use_oob = FALSE,
      token = NULL
    )
  } else {
    googlesheets4::gs4_deauth()
    googlesheets4::gs4_auth(
      email = "cansav09@gmail.com",
      scopes = c("https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"),
      cache = ".secrets/"
    )
  }
}
```


```{r echo = FALSE}
get_poster_id <- function(poster_id = "AMYAM4850U") {
poster_sheet <- "https://docs.google.com/spreadsheets/d/12aomFyT0zEHNmpyCQoGdDh16P-bRp4Pkt4PCCrU7gYY/edit"
authenticate()

poster_key <- googlesheets4::read_sheet(
  poster_sheet, 
  sheet = "posterpoller_id_key"
)

# Get URL query
query <- parseQueryString(session$clientData$url_search)
print(query)
if (is.null(query[["poster_id"]])) query[["poster_id"]] <- NA
  
poster_info <- poster_key %>% 
  dplyr::filter(poster_id == query[["poster_id"]])

return(poster_info)
}
```

```{r}
reactive({
  poster_info <- get_poster_id(poster_id = "AMYAM4850U")
  })

```


```{r }
output$UI <- renderUI({
  
h2("Poster Info:")
p("Does this info match the poster you wish to vote on? \n") 
p("Presenter:", poster_info$presenter_name, "\n")
p("Title:", poster_info$poster_title, "\n") 
selectInput("ranking", "Choose a ranking for this poster:",
            list(`Ranking` = list("First", "Second", "Third")))
      
actionButton("submit", "Submit", icon("fas fa-sync"))

})
```


```{r, echo = FALSE}
observeEvent(input$submit, {
  showModal(modalDialog(
    title = "Thank you for your vote!!",
    footer = NULL
  ))

    # Get URL query
    query <- parseQueryString(session$clientData$url_search)
    print(query)
    if (is.null(query[["course_name"]])) query[["course_name"]] <- NA

  response_data <- data.frame(
    time = Sys.time(),
    response = input$response,
    course = query[["course_name"]]
  )
  str(response_data)

  print(response_data)

  authenticate()
  googlesheets4::sheet_append(
    data = response_data,
    ss = "votes",
    sheet = "response_data"
  )

})
```

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-QML6KR0YVW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-QML6KR0YVW');
</script>
