---
title: ""
output: html_document
runtime: shiny
resource_files:
- .secrets/3db8733ded05fd02b7eb9bbac30624d9_cansav09@gmail.com
- README.md
---


```{r global, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(gsheet)
library(magrittr)
library(shiny)
library(googlesheets4)
library(googledrive)

authenticate <- function() {
  # designate project-specific cache
  options(gargle_oauth_cache = ".secrets")

  # check the value of the option, if you like
  gargle::gargle_oauth_cache()

  if (interactive()) {
    googlesheets4::gs4_deauth()
    googlesheets4::gs4_auth(
      email = "cansav09@gmail.com",
      path = NULL,
      scopes = c("https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"),
      # Get new token if it doesn't exist
      cache = ".secrets/",
      use_oob = FALSE,
      token = NULL
    )
  } else {
    googlesheets4::gs4_deauth()
    googlesheets4::gs4_auth(
      email = "cansav09@gmail.com",
      scopes = c("https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"),
      cache = ".secrets/"
    )
  }
}
```

```{r echo = FALSE}
tags$style(type = 'text/css', '
           #big_slider 
           .irs-grid-text {font-size: 20px} 
           .irs-grid-pol.small {height: 0px;} 
           .irs-min, .irs-max {visibility: hidden !important;}') 
div(id = 'big_slider', align = "center", sliderInput("response", "How likely are you to recommend this resource?", 6, min = 0, max = 10))
p(align = "center","0 = Not at all 10 = Absolutely")
div(align = "center", actionButton("submit", "Submit", icon("fas fa-sync")))
```


```{r, echo = FALSE}
observeEvent(input$submit, {
  showModal(modalDialog(
    title = "Thank you for your feedback!",
    footer = NULL
  ))

    # Get URL query
    query <- parseQueryString(session$clientData$url_search)
    print(query)
    if (is.null(query[["course_name"]])) query[["course_name"]] <- NA

  response_data <- data.frame(
    time = Sys.time(),
    response = input$response,
    course = query[["course_name"]]
  )
  str(response_data)

  print(response_data)

  authenticate()
  googlesheets4::sheet_append(
    data = response_data,
    ss = "https://docs.google.com/spreadsheets/d/1EZvP4nf0XBYQ2I1aBBF9ljoZpTtLds_JcOJqPfDIcYE/edit#gid=0",
    sheet = "response_data"
  )

})
```

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-QML6KR0YVW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-QML6KR0YVW');
</script>
